### ISSUE TITLE
Add requestDevice() callback hook to Web Bluetooth API

### ISSUE THREAD

**Issue by thegecko** [thegecko/bleat#10]
Add requestDevice() callback hook to allow headless implementations to select an appropriate device.

**Comment by jyasskin** [comment]
Once you specify this, I think I can add a note to the main specification pointing out that implementations without the browser's security concerns should look here for an API. Are you thinking that [`RequestDeviceOptions`](https://webbluetoothcg.github.io/web-bluetooth/#dictdef-requestdeviceoptions) would grow an `acceptDevice: BluetoothDevice=>boolean` argument?

**Comment by thegecko** [comment]
Thanks @jyasskin, I haven't given much thought to this, one way could be to have an ```deviceRequested(filters)``` hook which the developer could use. I like your suggestion, though. If I understand correctly,  the ```RequestDeviceOptions``` argument would be a function executed for every found/matched device until one returns true:

```
bluetooth.requestDevice({
        filters:[{ services:[ "heart_rate" ] }],
        acceptDevice: function(bluetoothDevice) {
                return (bluetoothDevice.name === "awesomeDevice"); // or similar
        }
})
```

**Comment by thegecko** [comment]
One scenario which this doesn't handle is when a UA (think noble on node) doesn't have a UI for selecting a device, but you want to be able to ask the user via a command-line. In this case, an optional function which lists all found devices could be more flexible:

```js
bluetooth.requestDevice({
    filters:[{ services:[ "heart_rate" ] }],
    acceptDevice: function(bluetoothDevices) {
    	// Choose device, perhaps listing all on command line or other UI
    	var bluetoothDevice = bluetoothDevices[0];
        return bluetoothDevice;
    }
})
```

I've currently get an extra ```requestDevices()``` function which covers this scenario, but the above function would negate the need for this and feels tidier.

**Comment by jyasskin** [comment]
If you want to show the user a UI, I think you actually want to get real-time notifications of advertising packets, like in other discovery APIs, rather than waiting until the scan times out to get all of them. You could have `acceptDevice` return a Promise, and have the scan `Promise.race()` them. Do you already have a way to wrap a Node device into a `BluetoothDevice` instance, for people who want to use that scanning API?

**Comment by thegecko** [comment]
No, I hide the implementation used entirely, so it's not possible to take a ```noble BLE``` device and turn it into a ```BluetoothDevice```.

I'm not quite sure what you mean by:

> have the scan race them

Are you suggesting each found device returns a Promise which the user could ```resolve()``` to choose that device?

**Comment by mikaelkindborg** [comment]
I work with hybrid apps (Cordova) and think it would be most useful to have an "extended" Web Bluetooth API for use when security is not of concern. I like what I have seen of the Web Bluetooth API, have spent the last couple of days updating the Bleat implementation for the cordova-ble plugin (https://github.com/evothings/cordova-ble).

Scanning for BLE devices (beacons) is a common scenario, and with Eddystone I believe this is going to be a popular use case. So having continuous scanning supported by the API is on my wishlist :)

I have no strong opinions on the API design, the Web Bluetooth API is still new to me, but I am happy to help and test new ideas and write example programs.

It would also be an advantage for developers to have a common Bluetooth API that works both in browsers and in other JavaScript environments.

**Comment by thegecko** [comment]
@jyasskin , @mikaelkindborg 
I've been thinking about an API we could use to cover headless/bespoke UI support for Web Bluetooth device selection, but haven't been able to find a clean solution.

I have three APIs so far, each with it's own drawbacks...

1) return all found devices into a declared callback function:

```js
bluetooth.requestDevice({
    filters:[{ services:[ "heart_rate" ] }],
    acceptDevice: function(bluetoothDevices) {
        var bluetoothDevice = bluetoothDevices[0];
        return bluetoothDevice;
    }
})
```

Advantages: clean and encapsulated approach
Drawbacks: the user has to wait for the scan to complete before seeing all devices and isn't easy to use to continually scan.

2) return found devices individually into a declared callback

```js
bluetooth.requestDevice({
    filters:[{ services:[ "heart_rate" ] }],
    acceptDevice: function(bluetoothDevice) {
        return (bluetoothDevice.name === "awesomeDevice"); // or similar
    }
})
```

Advantages: clean and encapsulated approach, continual scanning is possible, scanning immediately stops when device selected
Drawbacks: the user has to select a device only as it is found and without knowledge of previous devices and other devices yet to be found.

3) use an event to signify a new device is found and a function to select a device

```js
bluetooth.addEventListener('devicefound', function(event) {
	var device = event.target.bluetoothDevice;
	if (device.name === "bert") {
	    bluetooth.acceptDevice(device);
	}
});

bluetooth.requestDevice({
    filters:[{ services:[ "heart_rate" ] }]
})
```

Advantages: continual scanning is possible, scanning immediately stops when device selected, device can be selected at any time
Drawbacks: interface feels dirty and the devicefound event/acceptDevice function feel disconnected.

Any thoughts?

**Comment by mikaelkindborg** [comment]
@thegecko @jyasskin 

Perhaps an accept function could be passed to the found function to make the API less "scattered".
For example:

    bluetooth.requestDevice({
        filters:[{ services:[ "heart_rate" ] }],
        deviceFound: function(device, accept) {
            if (device.name === "bert") {
                accept(device);
            }
        }
    })

Or introduce start/stop scan functions:

    bluetooth.startScanning({
        filters:[{ services:[ "heart_rate" ] }],
        deviceFound: function(device) {
            if (device.name === "bert") {
                bluetooth.stopScanning();
            }
        }
    })

If there a way to used chaining with .then for the above? Need to call next .then only when found device is reported. Something like this:

    bluetooth.startScanning({
        filters:[{ services:[ "heart_rate" ] }]
    })
    .then(device -> {
        if (device.name === "bert") {
            bluetooth.stopScanning();
            return device;
        } else {
            // Is there a way to not call the next .then? return null?
        }
    })
    .then(device -> {
        // Connect to device.
        if (device) ...
    })

Feels a bit messy, but perhaps you can figure out a clean approach. Not entirely updated on promises...

**Comment by thegecko** [comment]
Thanks @mikaelkindborg, your first suggestion is similar to my 2) above and the user would have to choose a device only knowing the context of that single device.
I like the idea of using promises, but can't think of a neat way of doing it.

I wonder if a separate ```chooseDevice()``` function approach is the best of a bad bunch, something like:

```js
bluetooth.requestDevice({
    filters:[{ services:[ "heart_rate" ] }],
    // adding this function defers the Promise.resolve() of requestDevice()
    deviceFound: function(bluetoothDevice) {
        addDeviceToList(bluetoothDevice);
        // for synchronous requirements returning true here can stop scanning and
        // resolve Promise of requestDevice() with current bluetoothDevice
    }
})
.then(device => ...

var bluetoothDevices = [];
function addDeviceToList(bluetoothDevice) {
    bluetoothDevices.push(bluetoothDevice);
    // display found devices to the user
}

// event when user chooses a device
function handleUserSelect(index) {
    // 'choose' device stops scanning and resolves Promise of requestDevice()
    // with selected bluetoothDevice
    bluetooth.chooseDevice(bluetoothDevices[index]);
}
```

**Comment by mikaelkindborg** [comment]
@thegecko I was simply thinking the app would bypass the normal UI of requestDevice, do the device selection in a custom way (using a UI or programmatically), and do device.gatt.connect() and proceed. I guess there would be a need to stop scanning. Is that what bluetooth.chooseDevice() would do? The accept callback would do the same, just another way of getting hold of the function reference. But I think it is better and more explicit to have a named function.

What do you think about start/stop scanning functions? Would that not "play well" with the Web Bluetooth API?

**Comment by thegecko** [comment]
Yes, in this case ```chooseDevice()``` would stop scanning and allow the original ```requestDevice()``` to resolve, but perhaps that's too dependant and simply stopping the scan and using the bluetoothDevice would be simpler. As we already have a ```requestDevice()``` call, a ```startScan()``` isn't needed, just a ```cancelRequest()``` which stops scanning. How about:

```js
bluetooth.requestDevice({
    filters:[{ services:[ "heart_rate" ] }],
    // adding this function causes the Promise to resolve on timeout with no device, not reject
    deviceFound: function(bluetoothDevice) {
        addDeviceToList(bluetoothDevice);
        // for synchronous requirements returning true here can stop scanning and
        // resolve Promise of requestDevice() with current bluetoothDevice
    }
})
.then(...

var bluetoothDevices = [];
function addDeviceToList(bluetoothDevice) {
    bluetoothDevices.push(bluetoothDevice);
    // display found devices to the user
}

// event when user chooses a device
function handleUserSelect(index) {
    var bluetoothDevice = bluetoothDevices[index];

    // 'cancelRequest()' stops scanning and returns a promise
    bluetooth.cancelRequest()
    .then(() => {
        return bluetoothDevice.gatt.connect();
    })
    ...
}
```

**Comment by mikaelkindborg** [comment]
@thegecko Introducing bluetooth.cancelRequest() seems like a great approach.

As I understand it the requestDevice call would then not have a .then call following it?

This is how I would use cancelRequest, a variation on your code example:

	bluetooth.requestDevice({
		filters:[{ services:[ "heart_rate" ] }],
		deviceFound: function(bluetoothDevice) {
			if (someCondition) {
				bluetooth.cancelRequest();
				connectToDevice(bluetoothDevice);
			}
		}
	});

	function connectToDevice(bluetoothDevice) {
		bluetoothDevice.gatt.connect()
		.then(...)
		.then(...);
	}

It might be that chooseDevice() would also be useful, but perhaps a bit too "magical" (not obvious from the call that the .then call will evaluate). Perhaps it could be named resolveRequest()? Anyhow, I think it is fine to have only cancelRequest(), since this covers all use cases. Have you thought about the name? "Cancel" sort of implies aborting something, when in fact the code proceeds to connect to the device. Perhaps stopRequest() would fit better with the code flow? Just a thought.

**Comment by mikaelkindborg** [comment]
@thegecko Hi, is having something like bluetooth.chooseDevice() still an option you consider? 

As I understand it, we currently have alternative 2 as outlined above (
https://github.com/thegecko/bleat/issues/10#issuecomment-192234888).

It would be sweet to be able to resolve the promise with a device at any point, not having to explicitly returning it from deviceFound, as you mentioned when discussing drawbacks with  alternative 2. 

I am thinking for example of the scenario where a dynamic list of devices is presented to the user, for example Eddystone devices, and the list is dynamically updated with distance info etc as advertised data arrives. Then when the user selects a device, we want to resolve the requestDevice promise with it.

Made a few examples for how to implement this.

Here us the application code (requestDeviceFancyUI is assumed to display the dynamic UI): 

	requestDeviceFancyUI([{ services:[ "heart_rate" ] }])
	.then(device => ...)

Here is one approach to implementing requestDeviceFancyUI using the current API:

	function requestDeviceFancyUI(filters) {
		// Function that resolves the returned promise.
		var mResolve

		// Shows selection UI.
		function displayUI(device) {
			...
		}
	
		// Resolve requestDevice when device is selected by the user.
		onUIDeviceSelected(device => {
			bluetooth.cancelRequest(); // Stop scanning.
			mResolve(device);
		});
	
		// Update UI.
		function updateUI(device) {
			// Update UI with device
			...
		}
	
		// Display the UI.
		displayUI()

		// Return promise.
		return new Promise(function(resolve, reject) {
			mResolve = resolve
			bluetooth.requestDevice({
				filters: filters,
				deviceFound: updateUI
		});
	}

Here is an implementation using chooseDevice:

	function requestDeviceFancyUI(filters) {
		// Shows selection UI.
		function displayUI(device) {
			...
		}
	
		// Resolve requestDevice when device is selected by the user.
		onUIDeviceSelected(device => {
			bluetooth.chooseDevice(device);
		});
	
		// Update UI.
		function updateUI(device) {
			// Update UI with device
			...
		}
	
		// Display the UI.
		displayUI()
	
		// Return requestDevice promise.
		return bluetooth.requestDevice({
			filters: filters,
			deviceFound: updateUI
		});
	}

One potential issue is that relying on "global" functions for cancelRequest and chooseDevice is that this would not work when having multiple calls to requestDevice. 

Here is an alternative approach where resolve and reject functions are passed in the call to the foundDevice function (calling either of them would stop scanning and resolve the related requestDevice promise):

	function requestDeviceFancyUI(filters) {
		// Function that resolves the requestDevice promise.
		var mResolve

		// Shows selection UI.
		function displayUI(device) {
			...
		}
	
		// Resolve requestDevice when device is selected by the user.
		onUIDeviceSelected(device => {
			mResolve(device);
		});
	
		// Update UI.
		function updateUI(device, resolve, reject) {
			// Save resolve function (same function would be passed on each call).
			mResolve = resolve
		
			// Update UI with device
			...
		}
	
		// Display the UI.
		displayUI()
	
		// Return requestDevice promise.
		return bluetooth.requestDevice({
			filters: filters,
			deviceFound: updateUI
		});
	}

**Comment by thegecko** [comment]
@mikaelkindborg did you see the new ```example_node_selector.js``` example which does exactly what you are suggesting using this API?

I'd prefer to not resolve the ```requestDevice()``` call using something like ```chooseDevice()``` as it splits the code flow between chains.

The current selection has ```requestDevice()``` resolve after a scan finishes allowing continued scanning rather than waiting for a user to select a device. Using ```deviceFound```, a developer can list devices how they see fit and use one once selected, optionally cancelling the current scan using ```cancelRequest()```

**Comment by mikaelkindborg** [comment]
@thegecko Yes, looked at example_node_selector.js, what I was thinking is that handleDeviceFound  may never return true, if devices are reported only once, for example. Then I came to think about the global nature of cancelRequest(), thinking this is a problem if concurrent calls to requestDevice is allowed.

**Comment by thegecko** [comment]
In the case when ```handleDeviceFound``` doesn't return true, ```requestDevice()``` will naturally end once the scan timeout completes.

Considering the scenario of calling the ```requestDevice()``` twice in non-UA environments is valid, however. The chrome implementations I've seen block the UI with a modal dialog, preventing this scenario.

Perhaps an error should be thrown immediately if a scan is running?

**Comment by thegecko** [comment]
Tracked in #28

**Comment by mikaelkindborg** [comment]
@thegecko Rejecting requestDevice if it is ongoing sounds fine.

Thanks again for explaining role of the scan timeout.

**Comment by thegecko** [comment]
@jyasskin This is what we have come up with:

https://github.com/thegecko/bleat/blob/headless-selection/api_web-bluetooth.md

**Comment by thegecko** [comment]
@mikaelkindborg re-reading your post about wrapping a nice UI around this feature, this is how it could look with the current proposal:

```js
requestDeviceFancyUI([{ services:[ "heart_rate" ] }])
.then(device => ...)
```

```js
function requestDeviceFancyUI(filters) {
    return new Promise(function(resolve, reject) {
        var devices = [];

        bluetooth.requestDevice({
            filters: filters,
            deviceFound: deviceFoundFn
        })
        .catch(reject);

        function deviceFoundFn(device) {
            devices.push(device);
            // Update UI
        }

        // When user selects a device
        function chooseDevice(index) {
            var device = devices[index];

            bluetooth.cancelRequest()
            .then(() => resolve(device))
            .catch(reject);
        }
    });
}
```

**Comment by mikaelkindborg** [comment]
@thegecko Thanks for posting the UI selection example code!
