### ISSUE TITLE
Update evothings adapter to new specification

### ISSUE THREAD

**Issue by thegecko** [thegecko/bleat#13]

**Comment by mikaelkindborg** [comment]
@thegecko Hi, updated the Evothings adapter. Currently in this branch:

https://github.com/mikaelkindborg/bleat/tree/evothings-adapter-update

Tested the Web Bluetooth API with an example app I am working on. Discovery, read/write characteristics and notifications work.

Also done some testing with the Classic API and this does work. From what I can see handles are not used at all places by the the Classic API. For example, readCharacteristic uses the UUID: https://github.com/thegecko/bleat/blob/master/dist/api.classic.js#L217 But readDescriptor uses _handle: https://github.com/thegecko/bleat/blob/master/dist/api.classic.js#L235

**Comment by thegecko** [comment]
Great, do you want to create a PR?

I don't think the handle differences will cause an issue (as characteristic IDs are unique, descriptors are only unique to their characteristic), but I agree this should be consistent, I'll create an issue for it.

**Comment by mikaelkindborg** [comment]
Thanks will create a pull request.

The problem with handle vs UUID is that the underlying implementation needs to know that the value given in the _handle property is the handle passed in in the adapter functions. 

I am happy to help with this if needed.

**Comment by thegecko** [comment]
PR merged, closing issue
