### ISSUE TITLE
Int looses this when called after ready

### ISSUE THREAD

**Issue by tijmenvangulik** [thegecko/bleat#19]
I made a small bug fix in commit

https://github.com/tijmenvangulik/bleat/commit/ec7fe444d9b1cd25f3ae39eb76b8ac8e50ec3760

When init is called on ready everything works fine. When initialized at a later moment ( button bread for example) the init function looses the this because the internal function is called without bind. The bug fix was committed together with other changes so you need a manual merge

**Comment by thegecko** [comment]
Thanks, @tijmenvangulik.
I've recently removed the init() function from the classic API, do you think the issue still stands?

**Comment by tijmenvangulik** [comment]
I have not yet tested the new api , I wait till this api is ready, till that moment my fixed can be used, but I can imagine that you do not want to spent any time on the old api

Tijmen

**Comment by thegecko** [comment]
The new version (current master) supports both the old and Web Bluetooth APIs

**Comment by tijmenvangulik** [comment]
Thanks, I will test the new api . You can close the issue. When I still have this problem on the new api I will post a new issue.

**Comment by thegecko** [comment]
Thanks!
