### ISSUE TITLE
feature detection | off cordova module include RequireJS (evothings) error

### ISSUE THREAD

**Issue by Phoscur** [thegecko/bleat#2]
Loading the project in a chrome browser on a dev machine results in an error at line 145
```javascript
  if (root.cordova) {
```
```
Uncaught TypeError: Cannot read property 'cordova' of undefined
```
Fix line 33:
```javascript
        define(['bleat'], factory.bind(null, root));
```

How can I perform proper feature detection?
I guess it's straightforward:
```javascript
   bleat.init(function() { bleAvailable = true }, function() { bleAvailable = false; });
```

**Comment by Phoscur** [comment]
Updated my fix.

**Comment by thegecko** [comment]
Thanks for that.

Your feature detection solution is sane, I'd prefer to not expose the adapter array just yet.

**Comment by Phoscur** [comment]
Hi! Would you please release the fix? It's already the third time I had to apply the fix manually now.

Is it possible to initialize bluetooth without an app restart?

**Comment by thegecko** [comment]
Released.

Have you tried the init() command again?
