### ISSUE TITLE
Device-Filter && set a function for options.deviceFound

### ISSUE THREAD

**Issue by vladi4k** [thegecko/bleat#37]
**Device-Filter** is not used in [api.web-bluetooth.js](https://github.com/thegecko/bleat/blob/master/dist/api.web-bluetooth.js#L188), if the **options.deviceFound** function is defined

```javascript
if (!options.deviceFound) {
       deviceInfo = filterDevice(options, deviceInfo);
}
```

**It's not a bug, it's a feature**, but the code with Filter & deviceFound function is used for the [Exampels](https://github.com/thegecko/bleat/blob/master/examples/example_node_eddystone.js#L106-L107).

**Comment by thegecko** [comment]
well spotted :) I've been toying with replacing the deviceFound callback https://github.com/thegecko/bleat/issues/34 and would appreciate some feedback.
