### ISSUE TITLE
Support for reportning devices multiple times during scanning

### ISSUE THREAD

**Issue by mikaelkindborg** [thegecko/bleat#44]
The Bleat Classing API reports devices once when found. In for instance beacon applications devices need to be reported multiple times. Can we add support for this? Like a flag, function/setting to control scanning behaviour. I am happy to help with this.

Did a quick experiment, commented out the following line in api.classic.js:

    adapter.startScan(serviceUUIDs, function(deviceInfo) {
        var device = new Device(deviceInfo);
        //if (devices[device.address]) return;
        devices[device.address] = device;
        if (foundFn) foundFn(device);

This makes devices being reported multiple times.

One potential problem is if the application expects the device object to be the same between calls to foundFn. For example, the application might add custom properties to the device object. These would be lost with the above code. Properties need to be copied to prevent this problem.

**Edit:** Been thinking more about the idea of a "persistent" device object that has the same identity between calls to foundFn. Probably this is a bad idea, for example, if device sends multiple packets you would want a guarantee that the data is not overwritten by a concurrent operation. Now, JavaScript is single-threaded, but there may be Worker objects etc, so this could happen. Eddystone is an example of sending multiple packets. 

We used this technique ("persistent" device objects) in the Evothings EasyBLE library, but now I realize it is perhaps not the best solution. It would be better to have the application handle this, and this would also make for a cleaner separation between "model and view", so to speak.

**Comment by mikaelkindborg** [comment]
@thegecko Added implementation for an options object for bleat.startScan in this pull request: https://github.com/thegecko/bleat/pull/47

Example use:

    bleat.startScan(foundFn, completeFn, errorFn, { allowDuplicates: true });

Default is allowDuplicates: false

What do you think?

**Comment by thegecko** [comment]
I think this functionality is covered by the suggestion which has just appeared over at the WebBluetoothCG:

https://github.com/WebBluetoothCG/web-bluetooth/pull/239

Would implementing this interface add the support for beacons you need?

**Comment by mikaelkindborg** [comment]
It is a bit hard to read the proposal in the commit ;) Is there a web page with the content available?

The proposal is for Web Bluetooth, right? Would something similar to the updated proposal be used for Bleat Classic API? Is that what you mean? My update is for Bleat Classic API, not for Web Bluetooth.

**Comment by thegecko** [comment]
https://rawgit.com/jyasskin/web-bluetooth-1/scanning/scanning.html

**Comment by mikaelkindborg** [comment]
@thegecko Thanks for the link to the scanning proposal web page.

I don't understand how the proposal is related to the Bleat Classic API, are you planning to drop Bleat Classic?

**Comment by mikaelkindborg** [comment]
Here is a demo of BLE background scanning using the updated Bleat library:

**Comment by thegecko** [comment]
Sorry, I didn't realise you wanted to add this to the classic API.

**Comment by mikaelkindborg** [comment]
@thegecko Thanks! Updated the pull request!
