### ISSUE TITLE
Bleat Classic API: Retrieving services, charactertistics and descriptors independetly of UUID casing

### ISSUE THREAD

**Issue by mikaelkindborg** [thegecko/bleat#49]
To get objects for services, charactertistics and descriptors in Bleat Classic API, map indexing is used. 

Keys are UUIDs and these are case dependent.

Would there be a way to make UUIDs case independent?

For example, methods on device, service and characteristic objects?

Example:

    var service = device.getService(serviceUUID);
    var characteristic = characteristic.getCharacteristic(characteristicUUID);
    var descriptor = characteristic.getDescriptor(descriptorUUID);

The above functions would then convert the case of the supplied parameter, so that both upper and lower case UUIDs would work.

**Comment by thegecko** [comment]
I wrote the `bleatHelpers.getCanonicalUUID()` function to fully expand a uuid and help with matching.
You can always use `toUpperCase()` in JavaScript, but I don't understand why you need this (unless I've missed something and BLE UUIDs are case insensitive?)

**Comment by mikaelkindborg** [comment]
@thegecko Thanks, looks like ´bleatHelpers.getCanonicalUUID()´could be useful. In my experience hexadecimal numbers in general usually are case insensitive, and also UUIDs. I ran into this problem today when I had UUIDs specified in uppercase but they keys in the map were lower case. Was thinking this might be a problem others could run into.

**Comment by mikaelkindborg** [comment]
@thegecko My understanding is that the proposed functions are not really needed. Closing this issue.
