### ISSUE TITLE
Unable to resolve module `url` from [path]/node_modules/ws/lib/WebSocket.js 

### ISSUE THREAD

**Issue by mosesmc52** [thegecko/bleat#50]
Hi, 

I created a new React Native v 0.42.0 project with the following libraries installed

react-native-ble: 1.0.8
bleat: 0.1.1

In addition to the welcome page. I added the two following lines to load the bleat and noble and an remote android tablet. 

var noble = ('noble');
var bleat = require('bleat').classic;

Noble loads, but everytime I try to load bleat I get this error. 
**==============================================**
The development server returned error code: 500 

URL: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Unable to resolve module `url` from [path]/node_modules/ws/lib/WebSocket.js 
Module does not exist in the module map or in these directories 
/node_modules/

**===============================**

Would you have any suggestions how I can fix this error?

**Comment by thegecko** [comment]
That looks like an error with your websocket library, which I don't believe is anything to do with bleat.
