### ISSUE TITLE
discoverIncludedServices not implemented on Android for Noble

### ISSUE THREAD

**Issue by mosesmc52** [thegecko/bleat#51]
I'm using the noble bleat library to pair an external peripheral device via Blutooth to an Android phone. However, within the react-native-ble library the discoverIncludedServices library was not implemented which bleat calls. Is there a work around or what needs to be updated in order for bleat to work. 

Thanks,

Moses

**Comment by thegecko** [comment]
I'm not aware of a workaround for this. I would raise an issue with the author of `react-native-ble` if part of their implementation of the noble specification is missing.
