### ISSUE TITLE
Update return types of characteristic notification functions

### ISSUE THREAD

**Issue by thegecko** [thegecko/bleat#55]
https://webbluetoothcg.github.io/web-bluetooth/#bluetoothremotegattcharacteristic

 - BluetoothRemoteGATTCharacteristic.startNotifications -> Promise(BluetoothRemoteGATTCharacteristic)
 - BluetoothRemoteGATTCharacteristic.stopNotifications -> Promise(BluetoothRemoteGATTCharacteristic)

**Comment by glennra** [comment]
Is the solution to this simply calling `resolve(this)` instead of just `resolve` at [api.web-bluetooth.js lines 502](https://github.com/thegecko/bleat/blob/master/dist/api.web-bluetooth.js#L502) and [ 509](https://github.com/thegecko/bleat/blob/master/dist/api.web-bluetooth.js#L509) ?

**Comment by thegecko** [comment]
I think so. Same for stopNotifications, too.
