### ISSUE TITLE
Uncaught TypeError: b._addAdapter is not a function

### ISSUE THREAD

**Issue by glennra** [thegecko/bleat#57]
In cordova 7.0.1 I have created the hello world app from the docs. If I add the bleat files to the build and add a script tag in the index.html to load web-bluetooth.evothings.min.js then the following error occurs:
`Uncaught TypeError: b._addAdapter is not a function at web-bluetooth.evothings.min.js:53`
There is a similar error if I load the equivalent unminified scripts.
Is there some other dependency that I'm missing?

**Comment by thegecko** [comment]
Which version of bleat?

cc @mikaelkindborg

**Comment by glennra** [comment]
The version is the [latest from github]( https://github.com/thegecko/bleat/commit/5cdc870cb1110f49f2b084402b82f704e587e7aa).
I have since discovered the source of the problem. I was trying to run it in the browser platform, which uses Chrome, which doesn't load the scripts in the order specified in the html. It runs properly on android.

**Comment by thegecko** [comment]
In the browser it will use the native `navigator.bluetooth` which would explain the error.

**Comment by glennra** [comment]
When running in a Cordova app on the browser platform (Chrome on OSX), even after ensuring that the load order is correct I still get this error: 

`Uncaught TypeError: bleat._addAdapter is not a function`

As you say it uses the native `navigator.bluetooth` so in the UMD section of adapter.evothings.js shouldn't it not initialise the adapter if `navigator.bluetooth` is defined?
I.e.:
```
        if (!root.navigator.bluetooth) {
            factory(root, root.bleat, root.bleatHelpers);
        }
```

**Comment by thegecko** [comment]
Why are you using a web bluetooth shim if the browser you are using already has it?

**Comment by glennra** [comment]
It's a Cordova app, and I'm wanting to use the Cordova 'browser' platform for development.

On mobile platforms it will use the evothings ble plugin and on the  'browser' platform the native web bluetooth support. The web-bluetooth implementation [line 44](https://github.com/thegecko/bleat/blob/master/dist/api.web-bluetooth.js#L44) already seems to support this.

**Comment by thegecko** [comment]
I've added a guard against this in the latest release, let me know if it fixes your issue.

**Comment by glennra** [comment]
Yes it fixes the issue, thanks. Tested with Cordova 'browser' and 'android' platforms.

**Comment by thegecko** [comment]
Perfect!
