### ISSUE TITLE
noble/debug package dependency: Regular Expression Denial of Service

### ISSUE THREAD

**Issue by Phoscur** [thegecko/bleat#67]
`npm audit`
https://www.npmjs.com/advisories/534

**Comment by thegecko** [comment]
Feel free to open a PR with fixed deps.

**Comment by Phoscur** [comment]
@thegecko thanks for the prompt reaction! 
made a PR, but you might need to lay hand on it to get the same exact build out of it (due to the uglify update)

**Comment by thegecko** [comment]
Looks like it's no longer merging the packages together for the final files, so may take a little bit more work to fix.

Do you still need to use this library (e.g. old API or evothings support) as it's been superceded by this:

https://github.com/thegecko/webbluetooth

**Comment by Phoscur** [comment]
No, I was already thinking of removing the imports.. does that project implement advertising (like beacons?)

**Comment by thegecko** [comment]
I've fixed your PR, please see comments on https://github.com/thegecko/bleat/pull/68

**Comment by thegecko** [comment]
> does that project implement advertising

No, I don't think either can act in this way

**Comment by Phoscur** [comment]
So are you republishing with these security fixes? Why is the last version in this repo 0.17 and on npm 0.18?

**Comment by thegecko** [comment]
> are you republishing with these security fixes?

Done - 0.1.9
