### ISSUE TITLE
missing error parameter limits the way you can use the api

### ISSUE THREAD

**Issue by tijmenvangulik** [thegecko/bleat#9]
Before I start . Thank you for the great library this was just the api that I was looking for.
 
The errors are currently handled by a global error hander: 
 Characteristic.prototype.read = function(completeFn) {
        adapter.readCharacteristic(this, executeFn(completeFn), raiseError("read characteristic error"));
    };
This results into problems when you want to write code which does do the a second read after the first read was completed successfully or with an error. It would be easier to write this kind of code if all the routines also had an optional error handler. Something like this

Characteristic.prototype.read = function(completeFn,errorFn) {
        adapter.readCharacteristic(this, executeFn(completeFn), function (e) {
          if (errorFn) ErrorFn(e) 
         raiseError("read characteristic error")
        });
    };
Writing it this way makes all routines still backwards compatible.

An even nicer solution would be to get rid of all the completed and error functions by using ES6 promis using a poly fill. But this may be much work.I will also be happy with an optional error parameter But  even a promis can be done in a backwards compatible way because the functions do not yet return values.

**Comment by thegecko** [comment]
Thanks for the feedback. I intend to re-implement this library following the web-bluetooth specification once I find some time to put some effort in. That specification uses promises, so should be a nicer interface to work with.

Have a look at the web-bluetooth branch for progress so far.

**Comment by tijmenvangulik** [comment]
New solution looks very good to me.  Following the official standard is a very good idea.  Can't wait till it is ready.

**Comment by thegecko** [comment]
I've decided to keep both specifications, so will change this to an enhancement to add individual error callback functions to the classic API.

**Comment by tijmenvangulik** [comment]
Thanks i will check it out I also made a small bug fix in commit
https://github.com/tijmenvangulik/bleat/commit/ec7fe444d9b1cd25f3ae39eb76b8ac8e50ec3760

When bleat was initialized at a later moment the init function looses the this because the internal function is called without bind. The bug fix was committed together with other changes so you need a manual merge

Tijmen

**Comment by thegecko** [comment]
Can you open this as a new bug?
